clients/urls.py
from django.urls import path

# ---------------------------------
from . import views

app_name = 'clients'
urlpatterns = [
    path('', views.CustomerListView.as_view(), name='customers'),
    path('details/<int:pk>', views.get_customer_details, name='customer_details'),
    path('new-customer', views.add_new_customer, name='new_customer'),
    path('edit-customer/<int:pk>', views.edit_customer, name='edit_customer'),
    path('activate/customer/<int:pk>', views.activate_customer, name='activate_customer'),
    path('deactivate/customer/<int:pk>', views.deactivate_customer, name='deactivate_customer'),
    path('reports/', views.get_total_customer_combos, name='get_stats_customer')
]

easycomb/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('', include('easycomb_theme.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('clients/', include('clients.urls')),
    path('inventory/', include('inventory.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.get_all_orders, name='orders'),
    path('change_status/<int:pk>', views.change_status_order, name='change_status_order'),
    path('details/<int:pk>', views.get_order_details, name='order_details'),
    path('register_paid/<int:pk>', views.register_order_paid, name='register_order_paid'),
    path('new-order', views.add_new_order, name='new_order'),
    path('edit-order/<int:pk>', views.edit_order, name='edit_order'),
    path('delete/<int:pk>', views.delete_order, name='delete_order')
]

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
# Create your models here.
from clients.models import Customer
from inventory.models import Combo, Product

class Status(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name_plural = "Status"

    def __str__(self):
        return f'{self.name}'

class Order(models.Model):
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    paid_status = models.BooleanField(default=False)
    money_received = models.FloatField(default=0)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='orders')
    combos = models.ManyToManyField(Combo, through='OrderDetail')
    products = models.ManyToManyField(Product, through='OrderDetail')

    def __str__(self):
        return f'{self.id} - {self.customer.first_name}'


class OrderDetail(models.Model):
    combo = models.ForeignKey(Combo, on_delete=models.CASCADE, blank=True, null=True, related_name="get_orders")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='get_products')
    description = models.CharField(max_length=100, blank=True)
    price_combo = models.FloatField(default=0)
    price_product = models.FloatField(default=0)
    quantity = models.PositiveIntegerField(default=1)  


    def __str__(self):
        msg = ''
        if self.combo is None:
            msg = f'Order: {self.order.id} - {self.product.name} - {self.price_product} - {self.quantity}'
        elif self.product is None:
            msg = f'Order: {self.order.id} - {self.combo.name} - {self.price_combo} - {self.quantity}'
        return msg


class Income(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='incomes')
    date = models.DateField()
    amount = models.FloatField(default=0)

    def __str__(self):
        return f'{self.amount}'

orders/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

# --------------
from clients.models import Customer
from inventory.models import Combo
from .models import Order, OrderDetail, Income, Status


class ChangeStatusOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('status',)
        widgets = {
            'status': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            )
        }

class NewIncomeForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = '__all__'
        exclude = ('order',)
        widgets = {
            'date': forms.DateInput(
                attrs = {
                    'class': 'form-control datetimepicker-input',
                    'data-target': '#reservationdate'
                }
            ),
            'amount': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            )
        }


class NewOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        exclude = ('status','paid_status', 'money_received', 'combos', 'products')
        widgets = {
            'customer': forms.Select(
                attrs = {
                    'class': 'form-control select2bs4'
                }
            )
        }
    
    def __init__(self, *args, **kwargs):
        super(NewOrderForm, self).__init__(*args, **kwargs)
        customers = Customer.objects.filter(status=True)
        options = [(customer.id, customer.first_name) for customer in customers]
        self.fields['customer'].choices = options 

class NewOrderDetailForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        fields = '__all__'
        exclude = ('price_combo', 'price_product')
        widgets = {
            'combo': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ),
            'product': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ),
            'description': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'quantity': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            )   
        }
    
    def __init__(self, *args, **kwargs):
        super(NewOrderDetailForm, self).__init__(*args, **kwargs)
        self.fields['combo'].queryset = Combo.objects.filter(status=True)

OrderDetailInlineFormSet = forms.inlineformset_factory(
    Order,
    OrderDetail,
    form=NewOrderDetailForm,
    extra=1
)

orders/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import (
    F,
    ExpressionWrapper,
    FloatField,
    Sum
)
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse



# Create your views here.
from .forms import (
    NewOrderForm,
    OrderDetailInlineFormSet,
    NewIncomeForm,
    ChangeStatusOrderForm,
)
from clients.models import Customer
from inventory.models import Product, Combo
from .models import Order, Status


def is_valid_query(params):
    return params is not None and params != ''

def calculate_subtotals(order):
    order_details = order.get_products.all().annotate(
        subtotal_combos = ExpressionWrapper(
            F('price_combo') * F('quantity'), output_field=FloatField()
        ),
        subtotal_products = ExpressionWrapper(
            F('price_product') * F('quantity'), output_field=FloatField()
        )
    )
    return order_details

def calculate_products_quantites(order):
    products = Product.objects.all()

    product_quantities = [{'product': product.name, 'quantity': 0} for product in products]
    for order_detail in order.get_products.all():
        if order_detail.combo is not None:
            for combo_item in order_detail.combo.products.all():
                for product_quantity in product_quantities:
                    if product_quantity.get('product') == combo_item.product.name:
                        product_quantity.update(
                            {
                                'product': combo_item.product.name,
                                'quantity': product_quantity.get('quantity') + (combo_item.quantity * order_detail.quantity)
                            }
                        )
        else:
            for product_quantity in product_quantities:
                if product_quantity.get('product') == order_detail.product.name:
                    product_quantity.update(
                        {
                            'product': order_detail.product.name,
                            'quantity': order_detail.quantity
                        }
                    )
    
    return product_quantities

@login_required
def get_all_orders(request):
    
    customers = Customer.objects.filter(status=True).all()

    status = Status.objects.all()

    customer_id = request.GET.get('customer')

    status_id = request.GET.get('status')

    orders = Order.objects.all()

    if is_valid_query(customer_id) and int(customer_id) > 0:
        orders = orders.filter(customer=customers.get(pk=customer_id)).all()

    if is_valid_query(status_id) and int(status_id) > 0:
        orders = orders.filter(status=status.get(pk=status_id))

    return render(request, 'orders/orders.html', {
        'status_choices': status,
        'customers': customers,
        'orders': orders
    })

@login_required
def register_order_paid(request, pk):
    order = Order.objects.get(pk=pk)

    order_details = calculate_subtotals(order)

    total_combo = order_details.aggregate(Sum('subtotal_combos'))['subtotal_combos__sum']
    total_products = order_details.aggregate(Sum('subtotal_products'))['subtotal_products__sum']
    incomes_sum = order.incomes.all().aggregate(Sum('amount'))['amount__sum']
    if order.incomes.all().aggregate(Sum('amount'))['amount__sum'] is None:
        incomes_sum = 0.0

    if request.method == 'POST':
        form = NewIncomeForm(request.POST)

        if form.is_valid():
            new_income = form.save(commit=False)
            if new_income.amount > 0 and ((new_income.amount + incomes_sum) <= total_combo or (new_income.amount + incomes_sum) <= total_products):
                new_income.order = order
                new_income.save()
                return HttpResponseRedirect(reverse('orders:order_details', args=(pk,)))
            else:
                if new_income.amount == 0:
                    print('El monto tiene que ser mayor que cero')
                else:
                    print('El monto ingresado es mayor al total!')

    return render(request, 'orders/order-register-paid.html', {
        'order': order,
        'form': NewIncomeForm()
    })

@login_required
def get_order_details(request, pk):
    
    order = Order.objects.get(pk=pk)
    incomes = order.incomes.all()


    product_quantities = calculate_products_quantites(order)
    
    # get order's details and calculate subtotals
    order_details_with_subtotals = calculate_subtotals(order)

    quantity_sum = order.get_products.all().aggregate(total_quantity=Sum('quantity'))

    total_combo = order_details_with_subtotals.aggregate(Sum('subtotal_combos'))
    total_products = order_details_with_subtotals.aggregate(Sum('subtotal_products'))

    incomes_sum = order.incomes.all().aggregate(Sum('amount'))


    if not order.paid_status:
        if total_combo['subtotal_combos__sum'] == incomes_sum['amount__sum'] or total_products['subtotal_products__sum'] == incomes_sum['amount__sum']:
            order.paid_status = True
            order.save()

    return render(request, 'orders/order-details.html', {
        'combos_total': total_combo['subtotal_combos__sum'],
        'products_total': total_products['subtotal_products__sum'],
        'quantity_total': quantity_sum['total_quantity'], 
        'order': order,
        'incomes': incomes,
        'order_details_with_subtotals': order_details_with_subtotals,
        'product_quantities': product_quantities,
    })

@login_required
# open a transaction
@transaction.atomic
def add_new_order(request):
    if request.method == 'POST':
        form = NewOrderForm(request.POST)

        if form.is_valid():
            sid = transaction.savepoint()
            new_order = form.save(commit=False)
            new_order.status = Status.objects.first()
            new_order.save()
            # transaction now contains new_order.save()
            formset = OrderDetailInlineFormSet(request.POST, instance=new_order)
            
            if formset.is_valid():
                order_details = formset.save(commit=False)

                if not are_combos(order_details):
                    if check_stock(order_details):
                        for order_detail in order_details:
                            set_price(order_detail)
                            decrease_product_stock(order_detail.product, order_detail.quantity)
                            order_detail.save()
                        transaction.savepoint_commit(sid)
                        return HttpResponseRedirect(reverse('orders:orders'))
                    else:
                        transaction.savepoint_rollback(sid)
                if check_stock(order_details):
                    for order_detail in order_details:
                        set_price(order_detail)
                        for combo_item in order_detail.combo.products.all():
                            decrease_product_stock(combo_item.product, (order_detail.quantity * combo_item.quantity))
                        order_detail.save()
                    
                    transaction.savepoint_commit(sid)
                    return HttpResponseRedirect(reverse('orders:orders'))
                else:
                    transaction.savepoint_rollback(sid)

    return render(request, 'orders/order-add.html', {
        'form': NewOrderForm(),
        'formset': OrderDetailInlineFormSet()
    })

@login_required
def edit_order(request, pk):
    order = Order.objects.get(pk=pk)
    order_details_tem = order.get_products.all()
    if request.method == 'POST':
        form = NewOrderForm(request.POST, instance=order)
        
        if form.is_valid():

            formset = OrderDetailInlineFormSet(request.POST, instance=order)

            if formset.is_valid():
                order_details = formset.save(commit=False)

                if not are_combos(order_details):
                    if check_stock(order_details):
                        for order_detail in order_details:
                            set_price(order_detail)
                            decrease_product_stock(order_detail.product, order_detail.quantity)
                            order_detail.save()
                        return HttpResponseRedirect(reverse('orders:orders'))
                
                if check_stock(order_details):
                    for order_detail in order_details:
                        set_price(order_detail)
                        for combo_item in order_detail.combo.products.all():
                            for order_detail_tem in order_details_tem:
                                if order_detail_tem.combo.id == order_detail.combo.id and order_detail_tem.quantity < order_detail.quantity:
                                    decrease_product_stock(combo_item.product, ((order_detail.quantity - order_detail_tem.quantity) * combo_item.quantity))
                        order_detail.save()
                    
                    return HttpResponseRedirect(reverse('orders:orders'))



    return render(request, 'orders/order-edit.html', {
        'order': order,
        'form': NewOrderForm(instance=order),
        'formset': OrderDetailInlineFormSet(instance=order)
    })

@login_required
def change_status_order(request, pk):
    order = Order.objects.get(pk=pk)

    if request.method == 'POST':
        form = ChangeStatusOrderForm(request.POST)

        if form.is_valid():
            new_status = form.cleaned_data['status']
            order.status = new_status
            order.save()
            return HttpResponseRedirect(reverse('orders:orders'))

    return render(request, 'orders/order-edit-status.html', {
        'order': order,
        'form': ChangeStatusOrderForm(initial = {'status': order.status })
    })

@login_required
def delete_order(request, pk):
    order = Order.objects.get(pk=pk)

    if order is not None:
        for order_item in order.get_products.all():

orders/templates/orders/order-edit-status.html
{% extends 'easycomb_theme/layout.html' %}

{% load static %}

{% block section-title %}
Cambio de Estado
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <!-- general form elements -->
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col">
                    <div class="card-tools float-right">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse"
                            data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove"
                            data-toggle="tooltip" title="Remove">
                            <i class="fas fa-times"></i></button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col d-flex flex-column">
                    <h3 class="card-title"><span class="text-bold h3">Cliente: </span><a
                            href="{% url 'clients:customer_details' order.customer.id %}"><span
                                class="text-bold h2 text-info">{{ order.customer.first_name }}
                                {{ order.customer.last_name }}</span></a></h3>
                    <h4 class="card-title text-muted">
                        <span class="underline">Nro de Pedido: {{ order.id }}</span>
                    </h4>
                </div>
                <div class="col">
                    <h3 class="card-title float-right"><span class="text-bold h3">Fecha: </span><span
                            class="text-bold h2">{{ order.date|date:"d-m-Y" }}</span></h3>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="" method="post" role="form">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="{{ form.status.name }}">Estado</label>
                    {{ form.status }}
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{% url 'orders:orders' %}" class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-primary float-right">Cambiar Estado</button>
            </div>
        </form>

    </div>
</section>
<!-- /.content -->
{% endblock content %}

orders/templates/orders/orders.html
{% extends 'easycomb_theme/layout.html' %}

{% load static %}

{% block header-resource %}
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'easycomb_theme/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'easycomb_theme/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

<!-- DataTables -->
<link rel="stylesheet" href="{% static 'easycomb_theme/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet"
    href="{% static 'easycomb_theme/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
{% endblock header-resource %}

{% block section-title %}
Pedidos
<a data-toggle="tooltip" data-placement="right" title="Agregar pedido" id="btnAddOrder" class="btn btn-success btn-sm" href="{% url 'orders:new_order' %}"><i class="fas fa-plus-circle">
        Agregar</i></a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">



    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-lg-2">
                    <h3>Lista de pedidos</h3>
                </div>
                <div class="col">
                    <form method="get" class="form-inline">
                        <div class="form-group mr-2">
                            <label class="col-form-label mr-1" for="customer">Filtrar por cliente:</label>
                            <select class="form-control select2bs4" name="customer">
                                <option value="0" selected="selected">Elige un cliente..</option>
                                {% for customer in customers %}
                                <option value="{{ customer.id }}">{{ customer.first_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group mr-2">
                            <label class="col-form-label mr-1" for="customer">Filtrar por estado:</label>
                            <select class="form-control select2bs4" name="status">
                                <option value="0" selected>Elige un estado..</option>
                                {% for status_choice in status_choices %}
                                <option value="{{ status_choice.id }}">{{ status_choice.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button type="submit" class="btn btn-secondary">Filtrar</button>
                    </form>
                </div>
            </div>


        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="width: 5px;">
                            #
                        </th>
                        <th>
                            Cliente
                        </th>
                        <th>
                            Fecha
                        </th>
                        <th class="text-center">
                            Estado
                        </th>
                        <th class="text-center">
                            Pagado
                        </th>
                        <th style="width: 20%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>
                            {{ order.id }}
                        </td>
                        <td>
                            <a href="{% url 'clients:customer_details' order.customer.id %}">
                                {{ order.customer.first_name }} {{ order.customer.last_name }}
                            </a>
                        </td>
                        <td>
                            {{ order.date|date:"d F, Y" }}
                        </td>
                        <td class="text-center">
                            <a href="{% url 'orders:change_status_order' order.id %}">
                                {% if order.status.id == 1 %}
                                <span class="badge badge-warning">{{ order.status.name }}</span>
                                {% elif order.status.id == 2 %}
                                <span class="badge badge-dark">{{ order.status.name }}</span>
                                {% else %}
                                <span class="badge badge-primary">{{ order.status.name }}</span>
                                {% endif %}
                            </a>
                        </td>
                        <td class="text-center">
                            {% if order.paid_status %}
                            <span class="badge badge-success">Pagado</span>
                            {% else %}
                            <span class="badge badge-danger">Pendiente</span>
                            {% endif %}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="{% url 'orders:order_details' order.id %}">
                                <i class="fas fa-eye">
                                </i>
                            </a>
                            <a class="btn btn-info btn-sm" href="{% url 'orders:edit_order' order.id %}">
                                <i class="fas fa-pencil-alt">
                                </i>
                            </a>
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal"
                                data-target="#modal-default{{ order.id }}">
                                <i class="fas fa-trash">
                                </i>

                            </a>
                        </td>
                    </tr>
                    <!-- Modal to Delete combo -->
                    <div class="modal fade" id="modal-default{{ order.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar Pedido</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar el pedido con ID
                                        <strong>{{ order.id }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'orders:delete_order' order.id %}" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% empty %}
                    <tr>
                        <td></td>
                        <td>No hay pedidos nuevos.</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th style="width: 5px;">
                            #
                        </th>
                        <th>
                            Cliente
                        </th>
                        <th>
                            Fecha
                        </th>
                        <th class="text-center">
                            Estado
                        </th>
                        <th class="text-center">
                            Pagado
                        </th>
                        <th style="width: 20%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->


</section>

<!-- /.content -->
{% endblock content %}


{% block page-script %}

<!-- Select2 -->
<script src="{% static 'easycomb_theme/plugins/select2/js/select2.full.min.js' %}"></script>


<!-- DataTables -->
<script src="{% static 'easycomb_theme/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'easycomb_theme/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'easycomb_theme/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'easycomb_theme/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>

<script>

    $(document).ready(() => {

        $("#example1").DataTable({
            "responsive": true,
            "autoWidth": false,
        });

        //Initialize Select2 Elements
        $('.select2').select2();

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        });


      /* add a shortcut with key 'a' for add client button */
      document.onkeydown = function (evt) {
        const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
        if (keyCode === 65) {
          const href = $('#btnAddOrder').attr('href');
          window.location.href = href
        }
      };
    })
</script>
{% endblock page-script %}