easycomb/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('', include('easycomb_theme.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('clients/', include('clients.urls')),
    path('inventory/', include('inventory.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'
urlpatterns = [
    path('combos', views.get_all_combos, name='combos'),
    path('new-combo', views.add_new_combo, name='new_combo'),
    path('combos/<int:pk>', views.get_combo_detail, name='combo_details'),
    path('edit-combo/<int:pk>', views.edit_combo, name='edit_combo'),
    path('delete/combo/<int:pk>', views.delete_combo, name='delete_combo'),
    path('products', views.get_all_products, name='products'),
    path('new-product', views.add_new_product, name='new_product'),
    path('edit-product/<int:pk>', views.edit_product, name='edit_product'),
    path('delete/product/<int:pk>', views.delete_product, name="delete_product"),
    path('categories', views.get_all_categories, name="categories"),
    path('new-category', views.add_new_category, name='new_category'),
    path('delete/category/<int:pk>', views.delete_category, name="delete_category")
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.get_all_orders, name='orders'),
    path('change_status/<int:pk>', views.change_status_order, name='change_status_order'),
    path('details/<int:pk>', views.get_order_details, name='order_details'),
    path('register_paid/<int:pk>', views.register_order_paid, name='register_order_paid'),
    path('new-order', views.add_new_order, name='new_order'),
    path('edit-order/<int:pk>', views.edit_order, name='edit_order'),
    path('delete/<int:pk>', views.delete_order, name='delete_order')
]

inventory/models.py
from django.db import models

# Create your models here.
from easycomb_theme.models import Address, City

default_product_image = 'uploads/default-product.jpg'

class Category(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    stock = models.IntegerField(default=0)
    wholesale_price = models.FloatField()
    retail_price = models.FloatField()
    image = models.ImageField(upload_to='uploads/', default=default_product_image)

    def __str__(self):
        return f'{self.name}'


class Combo(models.Model):
    name = models.CharField(max_length=64)
    price = models.FloatField()
    product_list = models.ManyToManyField(Product, through='ComboDetail')
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ComboDetail(models.Model):
    combo = models.ForeignKey(Combo, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.product.name}'

inventory/forms.py
from django import forms
from .models import (
    Product,
    Category,
    Combo,
    ComboDetail
)


class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('stock',)
        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'description': forms.Textarea(
                attrs = {
                    'class': 'form-control',
                    'rows': '4'
                }
            ),
            'category': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ),
            'wholesale_price': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'retail_price': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'image': forms.ClearableFileInput(
                attrs = {
                    'class': 'custom-file-input'
                }
            )
        }


class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            )
        }


class NewComboForm(forms.ModelForm):
    class Meta:
        model = Combo
        fields = '__all__'
        exclude = ('product_list',)

        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'price': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            )
        }


class NewComboDetailForm(forms.ModelForm):
    class Meta:
        model = ComboDetail
        fields = '__all__'


        widgets = {
            'product': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ), 
            'quantity': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            )
        }


ComboDetailInlineFormSet = forms.inlineformset_factory(
    Combo, 
    ComboDetail, 
    form=NewComboDetailForm, 
    extra=4,
    max_num=4
)

inventory/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import ( 
    NewProductForm,
    NewCategoryForm,
    NewComboForm,
    ComboDetailInlineFormSet
)
from .models import (
    Product, 
    Category,
    Combo
)

@login_required
def get_all_combos(request):
    
    combos = Combo.objects.all()
    ok = 0
    for combo in combos:
        for item in combo.products.all():
            if item.product.stock >= item.quantity:
                ok += 1
        
        if ok == len(combo.products.all()):
            combo.status = True
            combo.save()
        else:
            combo.status = False
            combo.save()

        ok = 0
        

    return render(request, 'inventory/combos.html', {
        'combos': Combo.objects.all()
    })

@login_required
def add_new_combo(request):
    if request.method == 'POST':
        form = NewComboForm(request.POST)

        if form.is_valid():
            new_combo = form.save(commit=False)
            formset = ComboDetailInlineFormSet(request.POST, instance=new_combo)

            if formset.is_valid():
                new_combo.save()
                formset.save()
                return HttpResponseRedirect(reverse('inventory:combos'))

    return render(request, 'inventory/combo-add.html', {
        'form': NewComboForm(),
        'formset': ComboDetailInlineFormSet()
    })

@login_required
def edit_combo(request, pk):
    combo = Combo.objects.get(pk=pk)

    # if is a post request
    if request.method == 'POST':
        form = NewComboForm(request.POST, instance=combo)

        if form.is_valid():
            formset = ComboDetailInlineFormSet(request.POST, instance=combo)
            
            if formset.is_valid():
                form.save()
                formset.save()

                return HttpResponseRedirect(reverse('inventory:combos'))
    # if is a get request
    return render(request, 'inventory/combo-edit.html', {
        'combo': combo,
        'form': NewComboForm(instance=combo),
        'formset': ComboDetailInlineFormSet(instance=combo)
    })

@login_required
def delete_combo(request, pk):
    combo = Combo.objects.get(pk=pk)
    
    if combo is not None:
        combo.delete()
        return HttpResponseRedirect(reverse('inventory:combos'))

@login_required
def get_combo_detail(request, pk):
    return render(request, 'inventory/combo-detail.html', {
        'combo': Combo.objects.get(pk=pk)
    })

@login_required
def get_all_products(request):
    return render(request, 'inventory/products.html', {
        'products': Product.objects.all()
    })

@login_required
def add_new_product(request):

    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)

        if form.is_valid():
            new_product = form.save()

            if new_product is not None:
                return HttpResponseRedirect(reverse('inventory:products'))
        else:
            return render(request, 'inventory/product-add.html', {
                'form': NewProductForm()
            })

    return render(request, 'inventory/product-add.html', {
        'form': NewProductForm()
    })

@login_required
def edit_product(request, pk):
    product = Product.objects.get(pk=pk)
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('inventory:products'))

    return render(request, 'inventory/product-edit.html', {
        'form': NewProductForm(instance=product),
        'product': product
    })

@login_required
def delete_product(request, pk):
    product = Product.objects.get(pk=pk)

    if product is not None:
        product.delete()

        return HttpResponseRedirect(reverse('inventory:products'))

@login_required
def get_all_categories(request):
    return render(request, 'inventory/categories.html', {
        'categories': Category.objects.all()
    })

@login_required
def add_new_category(request):
    
    if request.method == 'POST':
        form = NewCategoryForm(request.POST)

        if form.is_valid():
            new_category = form.save()

            if new_category is not None:
                return HttpResponseRedirect(reverse('inventory:categories'))
        else:
            return render(request, 'inventory/category-add.html', {
                'form': NewCategoryForm()
            })

    return render (request, 'inventory/category-add.html', {
        'form': NewCategoryForm()
    })

@login_required
def delete_category(request, pk):
    category = Category.objects.get(pk=pk)

    if category is not None:
        category.delete()

        return HttpResponseRedirect(reverse('inventory:categories'))

inventory/templates/inventory/categories.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Categorias
<a id="btnAddCategory" class="btn btn-success" href="{% url 'inventory:new_category' %}">
    <i class="fas fa-plus-circle">
    </i>
    Agregar
</a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Categorias</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-simple projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th style="width: 50%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                    <tr>
                        <td>
                            #
                        </td>
                        <td>
                            <a>
                                {{ category.name }}
                            </a>
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="#">
                                <i class="fas fa-pencil-alt">
                                </i>
                                
                            </a>
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#modal-default{{ category.id }}">
                                <i class="fas fa-trash">
                                </i>
                                
                            </a>
                        </td>
                    </tr>
                    <!-- Modal to Delete category -->
                    <div class="modal fade" id="modal-default{{ category.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar Categoria</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar la categoria con nombre <strong>{{ category.name }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'inventory:delete_category' category.id %}" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
/* add a shortcut with key 'a' for add client button */
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 65) {
    const href = $('#btnAddCategory').attr('href');
    window.location.href = href
  }
};
</script>
{% endblock page-script %}

inventory/templates/inventory/category-add.html
{% extends 'easycomb_theme/layout.html' %}

{% block page-title %}
Añadir Categoria
{% endblock page-title %}


{% block content %}
<!-- Main content -->
<section class="content">
    <form action="{% url 'inventory:new_category' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Nueva Categoria</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                                <i class="fas fa-minus"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="{{ form.name.name }}">Nombre Categoria</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-2">
                <a href="{% url 'inventory:categories' %}" class="btn btn-secondary">Cancel</a>
                <input type="submit" value="Crear nueva Categoria" class="btn btn-success float-right">
            </div>
        </div>
    </form>
</section>
<!-- /.content -->
{% endblock content %}

inventory/templates/inventory/combo-add.html
{% extends 'easycomb_theme/layout.html' %}

{% load static %}

{% block section-title %}
Nueva Combo
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Nueva Combo</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{% url 'inventory:new_combo' %}" method="post" role="form">
            {% csrf_token %}
            <div class="card-body">
                <div class="form-group">
                    <label for="{{ form.name.name }}">Nombre Combo</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label for="{{ form.price.name }}">Precio Combo</label>
                    {{ form.price }}
                </div>

                <div class="row">
                    {% for form in formset %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    <div class="col col-md-6 col-lg-4">
                        <div class="card card-info">
                            <div class="card-header">
                                <h3 class="card-title">Producto</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="{{ form.product.name }}">Producto</label>
                                    {{ form.product }}
                                </div>
                                <div class="form-group">
                                    <label for="{{ form.quantity.name }}">Cantidad</label>
                                    {{ form.quantity }}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <!-- Este miniformulario maneja el inline -->
            {{ formset.management_form }}

            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{% url 'inventory:combos' %}" class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-primary float-right">Crear Nuevo Combo</button>
            </div>
        </form>

    </div>
</section>
<!-- /.content -->
{% endblock content %}

inventory/templates/inventory/combos.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Combos
<a id="btnAddCombo" class="btn btn-success btn-sm" href="{% url 'inventory:new_combo' %}"><i class="fas fa-plus-circle">
        Agregar</i></a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Combos</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Precio
                        </th>
                        <th class="text-center">
                            Estado
                        </th>
                        <th style="width: 20%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for combo in combos %}
                    <tr>
                        <td>
                            #
                        </td>
                        <td>
                            <a>
                                {{ combo.name }}
                            </a>
                        </td>
                        <td>
                            ${{ combo.price }}
                        </td>
                        <td class="project-state">
                            {% if combo.status %}
                            <span class="badge badge-success">Disponible</span>
                            {% else %}
                            <span class="badge badge-danger">Agotado</span>
                            {% endif %}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="{% url 'inventory:combo_details' combo.id %}">
                                <i class="fas fa-eye">
                                </i>

                            </a>
                            <a class="btn btn-info btn-sm" href="{% url 'inventory:edit_combo' combo.id %}">
                                <i class="fas fa-pencil-alt">
                                </i>

                            </a>
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#modal-default{{ combo.id }}">
                                <i class="fas fa-trash">
                                </i>

                            </a>
                        </td>
                    </tr>
                    <!-- Modal to Delete combo -->
                    <div class="modal fade" id="modal-default{{ combo.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar Combo</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar el combo con nombre <strong>{{ combo.name }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'inventory:delete_combo' combo.id %}" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
/* add a shortcut with key 'a' for add client button */
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 65) {
    const href = $('#btnAddCombo').attr('href');
    window.location.href = href
  }
};
</script>
{% endblock page-script %}

inventory/templates/inventory/products.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Productos
<a id="btnAddProduct" class="btn btn-success btn-sm" href="{% url 'inventory:new_product' %}"><i class="fas fa-plus-circle">
        Agregar</i></a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Productos</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th>
                            Nombre Producto
                        </th>
                        <th>
                            Precio Mayorista
                        </th>
                        <th>
                            Precio Minorista
                        </th>
                        <th>
                            Categoria
                        </th>
                        <th style="width: 8%" class="text-center">
                            Stock
                        </th>
                        <th style="width: 20%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td>
                            #
                        </td>
                        <td>
                            <a>
                                {{ product.name }}
                            </a>
                        </td>
                        <td>
                            ${{ product.wholesale_price }}
                        </td>
                        <td>
                            ${{ product.retail_price }}
                        </td>
                        <td>
                            {{ product.category }}
                        </td>
                        <td class="project-state">
                            {% if product.stock > 0 %}
                            <span class="badge badge-success">{{ product.stock }}</span>
                            {% else %}
                            <span class="badge badge-danger">{{ product.stock }}</span>
                            {% endif %}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="{% url 'inventory:edit_product' product.id %}">
                                <i class="fas fa-pencil-alt">
                                </i>

                            </a>
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#modal-default{{ product.id }}">
                                <i class="fas fa-trash">
                                </i>

                            </a>
                        </td>
                    </tr>
                    <!-- Modal to Delete product -->
                    <div class="modal fade" id="modal-default{{ product.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar Producto</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar el producto con nombre <strong>{{ product.name }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'inventory:delete_product' product.id %}" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% empty %}
                    <tr>
                        <td></td>
                        <td>No hay productos agregados.</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
/* add a shortcut with key 'a' for add client button */
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 65) {
    const href = $('#btnAddProduct').attr('href');
    window.location.href = href
  }
};
</script>
{% endblock page-script %}