clients/urls.py
from django.urls import path

# ---------------------------------
from . import views

app_name = 'clients'
urlpatterns = [
    path('', views.CustomerListView.as_view(), name='customers'),
    path('details/<int:pk>', views.get_customer_details, name='customer_details'),
    path('new-customer', views.add_new_customer, name='new_customer'),
    path('edit-customer/<int:pk>', views.edit_customer, name='edit_customer'),
    path('activate/customer/<int:pk>', views.activate_customer, name='activate_customer'),
    path('deactivate/customer/<int:pk>', views.deactivate_customer, name='deactivate_customer'),
    path('reports/', views.get_total_customer_combos, name='get_stats_customer')
]

easycomb/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('', include('easycomb_theme.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('clients/', include('clients.urls')),
    path('inventory/', include('inventory.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.get_all_orders, name='orders'),
    path('change_status/<int:pk>', views.change_status_order, name='change_status_order'),
    path('details/<int:pk>', views.get_order_details, name='order_details'),
    path('register_paid/<int:pk>', views.register_order_paid, name='register_order_paid'),
    path('new-order', views.add_new_order, name='new_order'),
    path('edit-order/<int:pk>', views.edit_order, name='edit_order'),
    path('delete/<int:pk>', views.delete_order, name='delete_order')
]

clients/models.py
from django.db import models

# Create your models here.
from easycomb_theme.models import City, Address

class Customer(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64, blank=True)
    phone = models.CharField(max_length=64, blank=True)
    status = models.BooleanField(default=True)
    city = models.ForeignKey(
        City, 
        on_delete=models.CASCADE, 
        blank=True,
        null=True
    )
    address = models.ForeignKey(
        Address, 
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )


    def __str__(self):
        return f'{self.first_name} {self.last_name}'

clients/forms.py
from django import forms

from .models import Customer

class NewCustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ('status',)
        widgets = {
            'first_name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'last_name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'phone': forms.NumberInput(
                attrs = {
                    'class': 'form-control',
                    'min': '0'
                }
            ),
            'city': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ),
            'address': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            )
        }

clients/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import (
    F,
    ExpressionWrapper,
    FloatField,
    Sum,
    Value as V
)
from django.db.models.functions import Coalesce
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator

# Create your views here.
from .models import Customer
from .forms import NewCustomerForm
from orders.models import OrderDetail
from suppliers.models import PurchaseDetail

def is_params_valid(params):
    return params != '' and params is not None

def calculate_total_orders(orders):
    total = 0
    for order in orders:
        order_details = order.get_products.all().annotate(
            subtotal_combos = ExpressionWrapper(
                F('price_combo') * F('quantity'), output_field=FloatField()
            ),
            subtotal_products = ExpressionWrapper(
                F('price_product') * F('quantity'), output_field=FloatField()
            )
        )
        total += order_details.aggregate(Sum('subtotal_combos'))['subtotal_combos__sum']
        total += order_details.aggregate(Sum('subtotal_products'))['subtotal_products__sum']

        money_received = order.incomes.all().aggregate(total=Coalesce(Sum('amount'), V(0)))
        total -= money_received['total']

    return total

class CustomerListView(ListView):
    model = Customer
    template_name = 'clients/customers.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CustomerListView, self).dispatch(request, *args, **kwargs)


@login_required
def get_customer_details(request, pk):
    customer = Customer.objects.get(pk=pk)

    total_to_paid = calculate_total_orders(customer.orders.filter(paid_status=False).all())

    return render(request, 'clients/customer-details.html', {
        'customer': customer,
        'orders': customer.orders.all(),
        'total_to_paid': total_to_paid
    })

@login_required
def add_new_customer(request):
    if request.method == 'POST':
        form = NewCustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            if not Customer.objects.filter(first_name__iexact=customer.first_name, last_name__iexact=customer.last_name).exists():
                customer.save()
                messages.success(request, 'Cliente Registrado!')
                return HttpResponseRedirect(reverse('clients:customers'))
            else:
                messages.error(request, 'Ya existe un cliente con ese nombre y apellido!')

    return render(request, 'clients/customer-add.html', {
        'form': NewCustomerForm()
    })

@login_required
def edit_customer(request, pk):
    customer = Customer.objects.get(pk=pk)
    if request.method == 'POST':
        form = NewCustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('clients:customers'))


    return render(request, 'clients/customer-edit.html', {
        'customer': customer,
        'form': NewCustomerForm(instance=customer)
    }) 

@login_required
def activate_customer(request, pk):
    customer = Customer.objects.get(pk=pk)
    if customer is not None:
        customer.status = True
        customer.save()
        return HttpResponseRedirect(reverse('clients:customers'))

@login_required
def deactivate_customer(request, pk):
    customer = Customer.objects.get(pk=pk)

    if customer is not None:
        customer.status = False
        customer.save()
        return HttpResponseRedirect(reverse('clients:customers'))

@login_required
def get_total_customer_combos(request):
    startDate = request.GET.get('startDate')
    endDate = request.GET.get('endDate')

    purchase_details = PurchaseDetail.objects.all().select_related('purchase')
    
    cost_purchases = purchase_details \
        .annotate(sub_total=ExpressionWrapper(F('cost') * F('quantity'), output_field=FloatField())) \
        .aggregate(total_cost=Sum('sub_total'))['total_cost']
    
    if cost_purchases is None:
        cost_purchases = 0

    order_details = OrderDetail.objects.all().select_related('order')
    
    customers_total_combos = order_details.exclude(combo=None) \
        .values('order__customer__first_name', 'order__customer__last_name') \
        .annotate ( 
            sub_total=Coalesce(Sum('quantity'), V(0)),
            monto=ExpressionWrapper(Sum(F('quantity') * F('price_combo')), output_field=FloatField()),
            money_received=Coalesce(Sum('order__incomes__amount'), V(0)),
            balance=F('monto') - F('money_received')
        )
    
    total_quantity = customers_total_combos.aggregate(total=Coalesce(Sum('sub_total'), V(0)))
    facturacion = customers_total_combos.aggregate(total=Coalesce(Sum('monto'), V(0)))

    revenue = 0
    try:
        revenue = facturacion['total'] - cost_purchases['total_cost']
    except Exception as ex:
        print(ex)


    if is_params_valid(startDate) and is_params_valid(endDate):
        customers_total_combos = order_details.exclude(combo=None) \
            .filter(order__date__range=[startDate, endDate]) \
            .values('order__customer__first_name', 'order__customer__last_name') \
            .annotate ( 
                sub_total=Coalesce(Sum('quantity'), V(0)),
                monto=ExpressionWrapper(Sum(F('quantity') * F('price_combo')), output_field=FloatField()),
                money_received=Coalesce(Sum('order__incomes__amount'), V(0)),
                balance=F('monto') - F('money_received')
            )
        total_quantity = customers_total_combos.aggregate(total=Coalesce(Sum('sub_total'), V(0)))
        facturacion = customers_total_combos.aggregate(total=Coalesce(Sum('monto'), V(0)))

        cost_purchases = purchase_details \
            .filter(purchase__date__exact=startDate) \
            .annotate(sub_total=ExpressionWrapper(F('cost') * F('quantity'), output_field=FloatField())) \
            .aggregate(total_cost=Coalesce(Sum('sub_total'), V(0)))
        try:
            revenue = facturacion['total'] - cost_purchases['total_cost']
        except Exception as ex:
            print(ex)

    return render(request, 'clients/reports.html', {
        'customers_total_combos': customers_total_combos,
        'total_quantity': total_quantity['total'],
        'facturacion': facturacion['total'],
        'total_cost': cost_purchases,
        'revenue': revenue
    })

clients/templates/clients/customer-add.html
{% extends 'easycomb_theme/layout.html' %}

{% load static %}


{% block section-title %}
Nuevo Cliente
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Nuevo Cliente</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form id="formNewCustomer" action="" method="post" role="form">
            {% csrf_token %}
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.first_name.name }}">Nombre</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.last_name.name }}">Apellido</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.phone.name }}">Celular</label>
                    {{ form.phone }}
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.address.name }}">Dirección</label>
                            {{ form.address }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.city.name }}">Ciudad</label>
                            {{ form.city }}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{% url 'clients:customers' %}" class="btn btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-primary float-right">Registrar Nuevo Cliente</button>
            </div>
        </form>

    </div>
</section>
<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
$('#id_first_name').focus();

/* add a shortcut with key 'enter' to submit the form */ 
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 13) {
    $('#formNewCustomer').submit();
  }
};
</script>
{% endblock page-script %}

clients/templates/clients/customer-details.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Detalle del Cliente
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col">
                                <div class="card-tools float-right">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"
                                        data-toggle="tooltip" title="Remove">
                                        <i class="fas fa-times"></i></button>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col d-flex flex-column">
                                <h3 class="card-title"><span class="text-bold h3">Cliente: </span><a href="#"><span
                                            class="text-bold h2 text-info">{{ customer.first_name.capitalize }}
                                            {{ customer.last_name.capitalize }}</span></a></h3>
                                <h4 class="card-title text-muted">
                                    <span class="underline">Cliente ID: {{ customer.id }}</span>
                                </h4>
                            </div>
                            <!-- <div class="col">
                                <h3 class="card-title float-right"><span class="text-bold h3">Fecha: </span><span
                                        class="text-bold h2">{{ order.date|date:"d-m-Y" }}</span></h3>
                            </div> -->
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 1%">
                                        ID
                                    </th>
                                    <th>
                                        Fecha
                                    </th>
                                    <th class="text-center">
                                        Estado
                                    </th>
                                    <th class="text-center">
                                        Pagado
                                    </th>
                                    <th class="text-center">
                                        Accion
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td>
                                        {{ order.id }}
                                    </td>
                                    <td>
                                        {{ order.date }}
                                    </td>
                                    <td class="text-center">
                                        {% if order.status.id == 1 %}
                                        <span class="badge badge-warning">{{ order.status.name }}</span>
                                        {% elif order.status.id == 2 %}
                                        <span class="badge badge-dark">{{ order.status.name }}</span>
                                        {% else %}
                                        <span class="badge badge-primary">{{ order.status.name }}</span>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if order.paid_status %}
                                        <span class="badge badge-success">Pagado</span>
                                        {% else %}
                                        <span class="badge badge-danger">Pendiente</span>
                                        {% endif %}
                                    </td>
                                    <td class="project-actions text-center">
                                        <a class="btn btn-primary btn-sm"
                                            href="{% url 'orders:order_details' order.id %}">
                                            <i class="fas fa-eye">
                                            </i>

                                        </a>
                                    </td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td></td>
                                    <td>No hay pedidos.</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->

                    <!-- Button trigger modal -->
                    <div class="card-footer">
                        <a href="{% url 'clients:customers' %}" class="btn btn-info float-right">Volver</a>
                    </div>
                </div>
                <!-- /.card -->
            </div>

            <div class="col-md-12 col-lg-6">
                <div class="card">
                    <div class="card-header bg-info">
                        <h3 class="card-title">Monto por cobrar</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i
                                    class="fas fa-times"></i>
                            </button>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <h3><span class="text-bold">Total:</span> ${{ total_to_paid }}</h3>
                    </div>
                    <!-- /.card-body -->
                </div>

            </div>

        </div>
    </div>
</section>
<!-- /.content -->
{% endblock content %}

clients/templates/clients/customer-edit.html
{% extends 'easycomb_theme/layout.html' %}

{% load static %}


{% block section-title %}
Editar Cliente
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Editar Cliente: {{ customer }}</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="" method="post" role="form">
            {% csrf_token %}
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.first_name.name }}">Nombre</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.last_name.name }}">Apellido</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="{{ form.phone.name }}">Celular</label>
                    {{ form.phone }}
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.address.name }}">Dirección</label>
                            {{ form.address }}
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="{{ form.city.name }}">Ciudad</label>
                            {{ form.city }}
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{% url 'clients:customers' %}" class="btn btn-secondary">Cancelar</a>
                <button type="submit" class="btn btn-primary float-right">Actualizar Datos</button>
            </div>
        </form>

    </div>
</section>
<!-- /.content -->
{% endblock content %}

clients/templates/clients/customers.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
    Clientes
    <a accesskey="a" id="btnAddClient" class="btn btn-success btn-sm" href="{% url 'clients:new_customer' %}"><i class="fas fa-plus-circle">
            Agregar (a)</i></a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Clientes</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            ID
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Apellido
                        </th>
                        <th>
                            Celular
                        </th>
                        <th>
                            Dirección
                        </th>
                        <th>
                            Ciudad
                        </th>
                        <th class="text-center">
                            Estado
                        </th>
                        <th style="width: 20%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for customer in object_list %}
                    <tr>
                        <td>
                            {{ customer.id}}
                        </td>
                        <td>
                            <a>
                                {{ customer.first_name }}
                            </a>
                        </td>
                        <td>
                            {{ customer.last_name }}
                        </td>
                        <td>
                            {{ customer.phone }}
                        </td>
                        <td>
                            {% if customer.address is not None %}
                            {{ customer.address }}
                            {% else %}

                            {% endif %}
                        </td>
                        <td>
                            {% if customer.city is not None %}
                            {{ customer.city }}
                            {% else %}

                            {% endif %}
                        </td>
                        <td class="project-state">
                            {% if customer.status %}
                            <span class="badge badge-success">Activo</span>
                            {% else %}
                            <span class="badge badge-danger">No activo</span>
                            {% endif %}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="{% url 'clients:customer_details' customer.id %}">
                                <i class="fas fa-eye">
                                </i>
                            </a>
                            <a class="btn btn-info btn-sm" href="{% url 'clients:edit_customer' customer.id %}">
                                <i class="fas fa-pencil-alt">
                                </i>

                            </a>
                            {% if customer.status %}
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal"
                                data-target="#modal-default{{ customer.id }}">
                                <i class="fas fa-minus-circle"></i>
                            </a>

                            {% else %}
                            <a class="btn btn-success btn-sm" href="#" data-toggle="modal"
                                data-target="#modal-default{{ customer.id }}">
                                <i class="fas fa-check-circle"></i>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    <!-- Modal to Delete customer -->
                    <div class="modal fade" id="modal-default{{ customer.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    {% if customer.status %}
                                        <h3 class="modal-title">Desactivar Cliente</h3>
                                    {% else %}
                                        <h3 class="modal-title">Activar Cliente</h3>
                                    {% endif %}
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    {% if customer.status %}
                                        <p class="h6">Estas seguro de desactivar el cliente con nombre
                                            <strong>{{ customer.first_name }}</strong>?</p>
                                    {% else %}
                                        <p class="h6">Estas seguro de activar el cliente con nombre
                                            <strong>{{ customer.first_name }}</strong>?</p>
                                    {% endif %}
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    {% if customer.status %}
                                        <a href="{% url 'clients:deactivate_customer' customer.id %}"
                                            class="btn btn-danger">Desactivar</a>
                                    {% else %}
                                        <a href="{% url 'clients:activate_customer' customer.id %}"
                                            class="btn btn-success">Activar</a>
                                    {% endif %}
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</section>

<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
/* add a shortcut with key 'a' for add client button */
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 65) {
    const href = $('#btnAddClient').attr('href');
    window.location.href = href
  }
};
</script>
{% endblock page-script %}