easycomb/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path('', include('easycomb_theme.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('clients/', include('clients.urls')),
    path('inventory/', include('inventory.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'
urlpatterns = [
    path('', views.get_all_orders, name='orders'),
    path('change_status/<int:pk>', views.change_status_order, name='change_status_order'),
    path('details/<int:pk>', views.get_order_details, name='order_details'),
    path('register_paid/<int:pk>', views.register_order_paid, name='register_order_paid'),
    path('new-order', views.add_new_order, name='new_order'),
    path('edit-order/<int:pk>', views.edit_order, name='edit_order'),
    path('delete/<int:pk>', views.delete_order, name='delete_order')
]

suppliers/urls.py
from django.urls import path

from . import views

app_name = 'suppliers'
urlpatterns = [
    path('', views.get_all_suppliers, name='suppliers'),
    path('new-supplier', views.add_new_supplier, name='new_supplier'),
    path('edit-supplier/<int:pk>', views.edit_supplier, name='edit-supplier'),
    path('delete/supplier/<int:pk>', views.delete_supplier, name='delete_supplier'),
    path('purchases', views.get_purchases, name='purchases'),
    path('delete/purchase/<int:pk>', views.delete_purchase, name='delete_purchase'),
    path('purchases/<int:pk>/detail', views.get_purchase_detail, name='purchase_detail'),
    path('new-purchase', views.add_new_purchase, name='new_purchase')
]

suppliers/models.py
from django.db import models

# Create your models here.
from easycomb_theme.models import Address, City
from inventory.models import Product



class Supplier(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64, blank=True)
    phone = models.CharField(max_length=64)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.first_name


class Purchase(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    date = models.DateField()
    remarks = models.CharField(max_length=100, blank=True, null=True)
    products = models.ManyToManyField(Product, through='PurchaseDetail')

    def __str__(self):
        return f'{self.supplier} - {self.date}'


class PurchaseDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE, related_name='products_purchased')
    description = models.CharField(max_length=100, blank=True, null=True)
    cost = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.purchase.supplier} {self.product.name} - {self.quantity} - ${self.cost}'
    

suppliers/forms.py
from django import forms

from .models import (
    Purchase,
    PurchaseDetail,
    Supplier
)


class NewSupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'last_name': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'phone': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'address': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ),
            'city': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            )
        }


class NewPurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'
        exclude = ('products', )

        widgets = {
            'supplier': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ),
            'date': forms.DateInput(
                attrs = {
                    'class': 'form-control datetimepicker-input',
                    'data-target': '#reservationdate'
                }
            ),
            'remarks': forms.TextInput (
                attrs = {
                    'class': 'form-control'
                }
            )
        }


class NewPurchaseDetailForm(forms.ModelForm):
    class Meta:
        model = PurchaseDetail
        fields = '__all__'
        # exclude = ('purchase', )

        widgets = {
            'product': forms.Select(
                attrs = {
                    'class': 'form-control custom-select'
                }
            ), 
            'description': forms.TextInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'cost': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            ),
            'quantity': forms.NumberInput(
                attrs = {
                    'class': 'form-control'
                }
            )
        }


PurchaseDetailInlineFormSet = forms.inlineformset_factory(
    Purchase, 
    PurchaseDetail, 
    form=NewPurchaseDetailForm, 
    extra = 4
)

suppliers/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import (
    F, 
    ExpressionWrapper, 
    FloatField
)
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse

# Create your views here.
from .forms import (
    NewPurchaseForm,
    NewPurchaseDetailForm,
    PurchaseDetailInlineFormSet,
    NewSupplierForm
)
from .models import (
    Supplier, 
    Purchase,
    Product
)

@login_required
def get_all_suppliers(request):
    return render(request, 'suppliers/suppliers.html', {
        'suppliers': Supplier.objects.all()
    })

@login_required
def add_new_supplier(request):

    if request.method == 'POST':
        form = NewSupplierForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('suppliers:suppliers'))

    return render(request, 'suppliers/supplier-add.html', {
        'form': NewSupplierForm()
    })

@login_required
def delete_supplier(request, pk):
    supplier = Supplier.objects.get(pk=pk)

    if supplier is not None:
        supplier.delete()

        return HttpResponseRedirect(reverse('suppliers:suppliers'))

@login_required
def edit_supplier(request, pk):
    supplier = Supplier.objects.get(pk=pk)

    if request.method == 'POST':
        
        form = NewSupplierForm(request.POST, instance=supplier)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('suppliers:suppliers'))

    return render(request, 'suppliers/supplier-edit.html', {
        'supplier': supplier,
        'form': NewSupplierForm(instance=supplier)
    })

@login_required
def get_purchases(request):
    return render(request, 'suppliers/purchases.html', {
        'purchases': Purchase.objects.all()
    })

@login_required
def get_purchase_detail(request, pk):
    
    purchase = Purchase.objects.get(pk=pk)

    totals = Purchase.objects.get(pk=pk).products_purchased.all().annotate(
        total=ExpressionWrapper(
            F('cost') * F('quantity'), output_field=FloatField()
        )
    )
    total_purchased = 0
    for i in totals:
        total_purchased += i.total

    return render(request, 'suppliers/purchase-detail.html', {
        'products_purchased': totals,
        'total_purchased': total_purchased
    })

@login_required
def add_new_purchase(request):

    if request.method == 'POST':
        form = NewPurchaseForm(request.POST)
        
        print(form.is_valid())

        if form.is_valid():
            purchase = form.save()
            formset = PurchaseDetailInlineFormSet(request.POST, instance=purchase)
            if formset.is_valid():
                new_purchases = formset.save(commit=False)
                for new_purchase in new_purchases:
                    # increase the product stock
                    Product.objects.filter(id=new_purchase.product.id).update(stock=F('stock') + new_purchase.quantity)
                    new_purchase.save()

                return HttpResponseRedirect(reverse('suppliers:purchases'))

    return render(request, 'suppliers/purchase-add.html', {
        'form': NewPurchaseForm(),
        'formset': PurchaseDetailInlineFormSet()
    })

@login_required
def delete_purchase(request, pk):
    purchase = Purchase.objects.get(pk=pk)

    if purchase is not None:
        purchase.delete()

        return HttpResponseRedirect(reverse('suppliers:purchases'))
    

suppliers/templates/suppliers/purchase-add.html
{% extends 'easycomb_theme/layout.html' %}

{% load static %}


{% block header-resource %}
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet"
    href="{% static 'easycomb_theme/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
{% endblock header-resource %}

{% block section-title %}
Nueva Compra
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">
    <!-- general form elements -->
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Nueva Compra</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{% url 'suppliers:new_purchase' %}" method="post" role="form">
            {% csrf_token %}
            <div class="card-body">
                <div class="row">
                    <div class="form-group col">
                        <label for="{{ form.supplier.name }}">Proveedor</label>
                        {{ form.supplier }}
                    </div>
                    <!-- Date -->
                    <div class="form-group col">
                        <label>Date:</label>
                        <div class="input-group date" id="reservationdate" data-target-input="nearest">
                            {{ form.date }}
                            <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-6">
                        <label for="{{ form.remarks.name }}">Descripcion</label>
                        {{ form.remarks }}
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="card card-info">
                            <div class="card-header">
                                <h3 class="card-title">Agregar Producto</h3>
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"
                                        data-toggle="tooltip" title="Collapse">
                                        <i class="fas fa-minus"></i></button>
                                </div>
                            </div>
                            {% for form in formset %}
                            <div class="card-body">
                                <div class="card">
                                    <div class="card-header bg-info">
                                    </div>
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="form-group col-12 col-lg-3">
                                                <label for="{{ form.product.name }}">Producto</label>
                                                {{ form.product }}
                                            </div>
                                            <div class="form-group col-12 col-lg-3">
                                                <label for="{{ form.description.name }}">Descripcion</label>
                                                {{ form.description }}
                                            </div>
                                            <div class="form-group col-12 col-lg-3">
                                                <label for="{{ form.cost.name }}">Costo por unidad</label>
                                                <div class="input-group mb-3">
                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text">$</span>
                                                    </div>
                                                    {{ form.cost }}
                                                    <div class="input-group-append">
                                                        <span class="input-group-text">.00</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group col-12 col-lg-3">
                                                <label for="{{ form.cost.name }}">Cantidad</label>
                                                {{ form.quantity }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

            <!-- Este miniformulario maneja el inline -->
            {{ formset.management_form }}

            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{% url 'suppliers:purchases' %}" class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-primary float-right">Registrar Nueva Compra</button>
            </div>
        </form>

    </div>
</section>
<!-- /.content -->
{% endblock content %}

{% block page-script %}
<!-- moment -->
<script src="{% static 'easycomb_theme/plugins/moment/moment.min.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script
    src="{% static 'easycomb_theme/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Page script -->
<script type="text/javascript">
    $(function () {
        //Date range picker
        $('#reservationdate').datetimepicker({
            format: 'YYYY-MM-DD'
        });
    });
</script>
{% endblock page-script %}

suppliers/templates/suppliers/purchase-detail.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Detalle de Compra
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Proveedores</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th>
                            Producto
                        </th>
                        <th>
                            Descripción
                        </th>
                        <th>
                            Costo
                        </th>
                        <th>
                            Cantidad
                        </th>
                        <th>
                            Total
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase_detail in products_purchased %}
                    <tr>
                        <td>
                            #
                        </td>
                        <td>
                            <a>
                                {{ purchase_detail.product.name }}
                            </a>
                        </td>
                        <td>
                            {{ purchase_detail.description }}
                        </td>
                        <td>
                            {{ purchase_detail.cost }}
                        </td>
                        <td>
                            {{ purchase_detail.quantity }}
                        </td>
                        <td>
                            $ {{ purchase_detail.total }}
                        </td>
                    </tr>
                    <!-- Modal to Delete product -->
                    <div class="modal fade" id="modal-default{{ product.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar producto</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar el producto con nombre <strong>{{ product.name }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="#" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% endfor %}
                    <tr class="bg-success">
                        <td>
                            
                        </td>
                        <td>
                            
                        </td>
                        <td>
                            
                        </td>
                        <td>
                            
                        </td>
                        <td>
                            <a>
                                Total
                            </a>
                        </td>
                        <td>
                            $ {{ total_purchased }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <a href="{% url 'suppliers:purchases' %}" class="btn btn-primary float-right">Volver</a>
        </div>
    </div>
    <!-- /.card -->

</section>

<!-- /.content -->
{% endblock content %}

suppliers/templates/suppliers/purchases.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Compras
<a id="btnAddPurchase" class="btn btn-success btn-sm" href="{% url 'suppliers:new_purchase' %}"><i class="fas fa-plus-circle">
    Agregar</i></a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Compras</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            ID
                        </th>
                        <th>
                            Proveedor
                        </th>
                        <th>
                            Fecha
                        </th>
                        <th style="width: 20%" class="text-center">
                            Accion
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase in purchases %}
                    <tr>
                        <td>
                            {{ purchase.id }}
                        </td>
                        <td>
                            <a>
                                {{ purchase.supplier.first_name  }}
                            </a>
                        </td>
                        <td>
                            {{ purchase.date }}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="{% url 'suppliers:purchase_detail' purchase.id %}">
                                <i class="fas fa-eye">
                                </i>
                            </a>
                            <a class="btn btn-info btn-sm" href="#">
                                <i class="fas fa-pencil-alt">
                                </i>

                            </a>
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#modal-default{{ purchase.id }}">
                                <i class="fas fa-trash">
                                </i>

                            </a>
                        </td>
                    </tr>
                    <!-- Modal to Delete purchase -->
                    <div class="modal fade" id="modal-default{{ purchase.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar Compra</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar el purchaseo con fecha <strong>{{ purchase.date }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'suppliers:delete_purchase' purchase.id %}" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% empty %}
                    <tr>
                        <td></td>
                        <td>No hay compras realizadas.</td>
                        <td></td>
                        <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
/* add a shortcut with key 'a' for add client button */
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 65) {
    const href = $('#btnAddPurchase').attr('href');
    window.location.href = href
  }
};
</script>
{% endblock page-script %}

suppliers/templates/suppliers/suppliers.html
{% extends 'easycomb_theme/layout.html' %}

{% block section-title %}
Proveedores
<a id="btnAddSupplier" class="btn btn-success btn-sm" href="{% url 'suppliers:new_supplier' %}"><i class="fas fa-plus-circle">
        Agregar</i></a>
{% endblock section-title %}

{% block content %}
<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Proveedores</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip"
                    title="Remove">
                    <i class="fas fa-times"></i></button>
            </div>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th style="width: 1%">
                            #
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Telefono
                        </th>
                        <th>
                            Direccion
                        </th>
                        <th>
                            Ciudad
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for supplier in suppliers %}
                    <tr>
                        <td>
                            #
                        </td>
                        <td>
                            <a>
                                {{ supplier.first_name }}
                            </a>
                        </td>
                        <td>
                            {{ supplier.phone }}
                        </td>
                        <td>
                            {{ supplier.address }}
                        </td>
                        <td>
                            {{ supplier.city }}
                        </td>
                        <td class="project-actions text-center">
                            <a class="btn btn-primary btn-sm" href="#">
                                <i class="fas fa-eye">
                                </i>
                            </a>
                            <a class="btn btn-info btn-sm" href="{% url 'suppliers:edit-supplier' supplier.id %}">
                                <i class="fas fa-pencil-alt">
                                </i>

                            </a>
                            <a class="btn btn-danger btn-sm" href="#" data-toggle="modal"
                                data-target="#modal-default{{ supplier.id }}">
                                <i class="fas fa-trash">
                                </i>
                            </a>
                        </td>
                    </tr>
                    <!-- Modal to Delete supplier -->
                    <div class="modal fade" id="modal-default{{ supplier.id }}">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title">Borrar Proveedor</h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p class="h6">Estas seguro de borrar el suppliero con nombre
                                        <strong>{{ supplier.first_name }}</strong>?</p>
                                </div>
                                <div class="modal-footer justify-content-between">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                    <a href="{% url 'suppliers:delete_supplier' supplier.id %}" class="btn btn-danger">Borrar</a>
                                </div>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    {% empty %}
                    <tr>
                      <td></td>
                      <td class="text-center">No hay datos disponibles</td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>

<!-- /.content -->
{% endblock content %}

{% block page-script %}
<script type="text/javascript">
/* add a shortcut with key 'a' for add client button */
document.onkeydown = function (evt) {
  const keyCode = evt ? (evt.which ? evt.which : evt.keyCode) : event.keyCode;
  if (keyCode === 65) {
    const href = $('#btnAddSupplier').attr('href');
    window.location.href = href
  }
};
</script>
{% endblock page-script %}